/// @file detector.hpp
/// @brief This file holds the Layer-2 Named Detector generator
///        macros.
///
/// See docs/adr/0006-detector-naming-calculus.md for the full design
/// rationale. This file is the how reference: the exact calculus for
/// adding a new Entity or a new Named Detector, including by hand
/// when the generator does not fit.
///
/// ## Layer 1 (Detector) — always hand-written, never generated
///
/// Every Entity header (`gcc.hpp`, `clang.hpp`, `standard.hpp`, ...)
/// hand-writes the same eleven-line pattern once. For an entity `ns`
/// seeded from some raw compiler/library macro:
///
/// ```cpp
/// #define BRIDGE_RIVETS_NS_VERSION ...        // seeded from a raw macro
///
/// namespace bridge::rivets::ns {
/// inline constexpr int version = BRIDGE_RIVETS_NS_VERSION;
/// constexpr bool gt(int n) { return version > n; }
/// constexpr bool ge(int n) { return version >= n; }
/// constexpr bool lt(int n) { return version < n; }
/// constexpr bool le(int n) { return version <= n; }
/// constexpr bool eq(int n) { return version == n; }
/// } // namespace bridge::rivets::ns
///
/// #define BRIDGE_RIVETS_NS_GT(n) (BRIDGE_RIVETS_NS_VERSION > (n))
/// #define BRIDGE_RIVETS_NS_GE(n) (BRIDGE_RIVETS_NS_VERSION >= (n))
/// #define BRIDGE_RIVETS_NS_LT(n) (BRIDGE_RIVETS_NS_VERSION < (n))
/// #define BRIDGE_RIVETS_NS_LE(n) (BRIDGE_RIVETS_NS_VERSION <= (n))
/// #define BRIDGE_RIVETS_NS_EQ(n) (BRIDGE_RIVETS_NS_VERSION == (n))
/// ```
///
/// This pattern is hand-written, not generated, for a hard reason. A
/// macro expansion can never emit a `#define` as a side effect. The
/// standard says the fully-expanded replacement text of a macro
/// invocation "is not processed as a preprocessing directive even if
/// it resembles one" ([cpp.rescan]). Six of these eleven lines are
/// `#define`s. So no generator could ever produce them. This file's
/// authors also write the other five lines, the constexpr
/// comparators, by hand, right alongside. This keeps the whole
/// pattern visible in one place, instead of splitting "some of this
/// entity's detector is generated, some isn't" across two
/// mechanisms.
///
/// ## Layer 2 (Named Detector) — generated by this file's macros
///
/// A Named Detector is just ordinary C++ code, a function
/// declaration. Macro expansion can legally produce this. This file
/// offers two forms:
///
/// - `BRIDGE_RIVETS_DEFINE_DETECTOR(ns, cmp, n)`: a single bound.
///   `BRIDGE_RIVETS_DEFINE_DETECTOR(gcc, gt, 12)` defines
///   `bridge::rivets::gcc::gt_12()`.
/// - `BRIDGE_RIVETS_DEFINE_DETECTOR_RANGE(ns, cmp1, n1, cmp2, n2)`:
///   two bounds, concatenated in order.
///   `BRIDGE_RIVETS_DEFINE_DETECTOR_RANGE(gcc, ge, 10, lt, 13)`
///   defines `bridge::rivets::gcc::ge_10_lt_13()`.
///
/// Neither form produces a named `#if`-usable macro
/// (`BRIDGE_RIVETS_GCC_GT_12`), for the same [cpp.rescan] reason
/// Layer 1 is not generated. When you genuinely want one, write it
/// directly:
///
/// ```cpp
/// #define BRIDGE_RIVETS_GCC_GT_12 BRIDGE_RIVETS_GCC_GT(12)
/// ```
///
/// That line is not a fallback for an awkward case. It is the only
/// mechanism by which any named macro ever comes to exist. Layer 1's
/// function-like macro, `BRIDGE_RIVETS_GCC_GT(12)`, already covers
/// this value in `#if` without it. The named alias above exists
/// purely for readability at specific call sites, exactly like Layer
/// 2's constexpr alias does for `if constexpr`.
#pragma once

/// @def BRIDGE_RIVETS_DEFINE_DETECTOR
/// @brief This macro generates a Named Detector:
///        `bridge::rivets::<ns>::<cmp>_<n>()`.
/// @param ns The Entity namespace, for example `gcc`, already defining `cmp`.
/// @param cmp One of `gt`, `ge`, `lt`, `le`, `eq`.
/// @param n The version number to compare against.
#define BRIDGE_RIVETS_DEFINE_DETECTOR(ns, cmp, n)                            \
    namespace bridge::rivets::ns {                                           \
    /** @brief This is a Named Detector. This checks whether ns's version cmp n. \
     *  @return Whether ns's version satisfies cmp n. */                     \
    constexpr bool cmp##_##n() { return ns::cmp(n); }                        \
    }

/// @def BRIDGE_RIVETS_DEFINE_DETECTOR_RANGE
/// @brief This macro generates a range Named Detector:
///        `bridge::rivets::<ns>::<cmp1>_<n1>_<cmp2>_<n2>()`.
/// @param ns The Entity namespace, for example `gcc`, already defining `cmp1`/`cmp2`.
/// @param cmp1 The lower-bound comparator, one of `gt`, `ge`, `lt`, `le`, `eq`.
/// @param n1 The lower-bound version number.
/// @param cmp2 The upper-bound comparator, one of `gt`, `ge`, `lt`, `le`, `eq`.
/// @param n2 The upper-bound version number.
#define BRIDGE_RIVETS_DEFINE_DETECTOR_RANGE(ns, cmp1, n1, cmp2, n2)          \
    namespace bridge::rivets::ns {                                           \
    /** @brief This is a Named Detector. This checks whether ns's version cmp1 n1 and cmp2 n2. \
     *  @return Whether ns's version satisfies both bounds. */               \
    constexpr bool cmp1##_##n1##_##cmp2##_##n2() {                           \
        return ns::cmp1(n1) && ns::cmp2(n2);                                 \
    }                                                                        \
    }
